services:
  apiwaverelease:
    build:
      context: ..
      dockerfile: APIWaveRelease/Dockerfile
    image: apiwaverelease:latest
    ports:
      - "5000:8080"
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  apilpnpicking:
    build:
      context: ..
      dockerfile: APILPNPicking/Dockerfile
    image: apilpnpicking:latest
    ports:
      - "5001:8080"
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  apifamilymaster:
    build:
      context: ..
      dockerfile: APIFamilyMaster/Dockerfile
    image: apifamilymaster:latest
    ports:
      - "5002:8080" # Puerto externo 5002 mapeado al puerto interno 8080
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped
  authservices:
    build:
      context: ..
      dockerfile: AuthServices/Dockerfile
    image: authservices:latest
    ports:
      - "5003:8080"
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  orderupdate:
    build:
      context: ..
      dockerfile: APIOrderUpdate/Dockerfile
    image: orderupdate:latest
    ports:
      - "5004:8080"
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

  apiorderconfirmation:
    build:
      context: ..
      dockerfile: APIOrderConfirmation/Dockerfile
    image: apiorderconfirmation:latest
    ports:
      - "5005:8080"
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped


  apisenad:
    build:
      context: ..
      dockerfile: APISenad/Dockerfile
    image: apisenad:latest
    ports:
      - "5006:8080"
    networks:
      - microservices-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped

networks:
  microservices-net:
    driver: bridge
